### ISSUE TITLE
How to install on HAOS X86?

### ISSUE THREAD

**Issue by ccbadd** [wernerhp/ha.addon.acme_sh#6]
Sorry for the dumb question but I just can't seem to figure out how to install this addon.  I am running a small HP computer using HAOS X86-64 and I can't find this addon via the GUI and I don't see any instructions on how to install it.  Any help would be apprecieated.

**Comment by wernerhp** [comment]
![image](https://user-images.githubusercontent.com/2578772/198829571-e41d46a1-292f-42e7-97dc-cd5c8b7a71e6.png)

![image](https://user-images.githubusercontent.com/2578772/198829561-579825e1-99c8-4351-9826-4a6e50a2d91e.png)

![image](https://user-images.githubusercontent.com/2578772/198829635-b719f503-5aea-4598-9cc4-ecfd406183dc.png)
![image](https://user-images.githubusercontent.com/2578772/198829644-b7347e00-cf7b-4488-83bd-bad3434e5793.png)
![image](https://user-images.githubusercontent.com/2578772/198829660-f55b9028-41e1-4f04-aef6-e3d182629350.png)



It may not be supported by your setup.  See https://www.home-assistant.io/installation/#compare-installation-methods
![image](https://user-images.githubusercontent.com/2578772/198829604-e0581f12-e49a-47eb-9658-abb34dd289db.png)
